export function mermaidConfiguration({ dark = false, fontFamily } = {}) {
  const colors = dark
    ? {
        background: "#24282e",
        primaryColor: "#303740",
        primaryTextColor: "#e4e8ed",
        primaryBorderColor: "#687585",
        secondaryColor: "#313b44",
        secondaryTextColor: "#e4e8ed",
        secondaryBorderColor: "#758594",
        tertiaryColor: "#383840",
        tertiaryTextColor: "#e4e8ed",
        tertiaryBorderColor: "#7a7889",
        lineColor: "#a3afbd",
        textColor: "#e4e8ed",
        clusterBkg: "#292f36",
        clusterBorder: "#566372",
        edgeLabelBackground: "#24282e",
        noteBkgColor: "#333b43",
        noteTextColor: "#e4e8ed",
        noteBorderColor: "#758594",
        actorBkg: "#303740",
        actorBorder: "#687585",
        actorTextColor: "#e4e8ed",
        actorLineColor: "#a3afbd",
        signalColor: "#a3afbd",
        signalTextColor: "#e4e8ed",
        labelBoxBkgColor: "#303740",
        labelBoxBorderColor: "#687585",
        labelTextColor: "#e4e8ed",
        loopTextColor: "#e4e8ed",
        activationBkgColor: "#414c59",
        activationBorderColor: "#8493a4",
      }
    : {
        background: "#f2f4f6",
        primaryColor: "#e8edf2",
        primaryTextColor: "#2c3541",
        primaryBorderColor: "#99a8b8",
        secondaryColor: "#e9efef",
        secondaryTextColor: "#2c3541",
        secondaryBorderColor: "#9aadb0",
        tertiaryColor: "#eeecf2",
        tertiaryTextColor: "#2c3541",
        tertiaryBorderColor: "#aaa4b7",
        lineColor: "#738194",
        textColor: "#2c3541",
        clusterBkg: "#edf0f3",
        clusterBorder: "#b3bdc9",
        edgeLabelBackground: "#f2f4f6",
        noteBkgColor: "#e9efef",
        noteTextColor: "#2c3541",
        noteBorderColor: "#9aadb0",
        actorBkg: "#e8edf2",
        actorBorder: "#99a8b8",
        actorTextColor: "#2c3541",
        actorLineColor: "#738194",
        signalColor: "#738194",
        signalTextColor: "#2c3541",
        labelBoxBkgColor: "#e8edf2",
        labelBoxBorderColor: "#99a8b8",
        labelTextColor: "#2c3541",
        loopTextColor: "#2c3541",
        activationBkgColor: "#dbe2ea",
        activationBorderColor: "#99a8b8",
      }
  return {
    startOnLoad: false,
    securityLevel: "strict",
    theme: "base",
    htmlLabels: false,
    flowchart: { htmlLabels: false, curve: "basis", padding: 18, nodeSpacing: 36, rankSpacing: 44 },
    sequence: { useMaxWidth: true, diagramMarginX: 24, diagramMarginY: 24 },
    maxTextSize: 50000,
    maxEdges: 300,
    suppressErrorRendering: true,
    secure: [
      "secure",
      "securityLevel",
      "startOnLoad",
      "maxTextSize",
      "maxEdges",
      "suppressErrorRendering",
      "htmlLabels",
      "flowchart",
      "sequence",
      "themeCSS",
      "themeVariables",
      "theme",
      "dompurifyConfig",
      "fontFamily",
      "fontSize",
    ],
    themeVariables: {
      ...colors,
      darkMode: dark,
      fontFamily:
        fontFamily ||
        '-apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif',
      fontSize: "15px",
    },
  }
}
